export interface ImageStyleDef {
  id: string;
  label: string;
  promptSuffix: string;
  promptSuffixReference: string;
}

// Canonical NB2 style copy (rev-7 plan §14): every named style trimmed to
// medium/technique + constitutive attributes only (scene content lives in the
// visual concept, not the style), each ≤ RENDER_STYLE_COPY_MAX_CHARS. `look_styles`
// DB rows are the runtime source of truth after migration 0088; this table is the
// seed/fallback, and a test asserts the two agree.
export const IMAGE_STYLES: ImageStyleDef[] = [
  { id: "none", label: "Default (No Style)", promptSuffix: "", promptSuffixReference: "" },
  { id: "cinematic", label: "Cinematic", promptSuffix: "Rendered in cinematic film style: the look of a widescreen movie still with filmic color grading, volumetric lighting, and subtle lens flare.", promptSuffixReference: "Reimagine this scene in cinematic film style: the look of a widescreen movie still with filmic color grading, volumetric lighting, and subtle lens flare." },
  { id: "epic", label: "Epic / Mythological", promptSuffix: "Depicted in epic mythological painting style: Renaissance-inspired composition with baroque intensity, dramatic scale, and grand painterly lighting.", promptSuffixReference: "Transform this into epic mythological painting style: Renaissance-inspired composition with baroque intensity, dramatic scale, and grand painterly lighting." },
  { id: "anime", label: "Anime", promptSuffix: "Illustrated in detailed Japanese anime style: bold outlines, cel-shaded rendering, expressive features, and vibrant color saturation.", promptSuffixReference: "Reimagine this person/scene in detailed Japanese anime style: bold outlines, cel-shaded rendering, expressive features, and vibrant color saturation." },
  { id: "comic", label: "Comic Book", promptSuffix: "Drawn in bold American comic book style: heavy black ink outlines, halftone dot shading, vivid flat colors, and dramatic foreshortening.", promptSuffixReference: "Transform this into bold American comic book style: heavy black ink outlines, halftone dot shading, vivid flat colors, and dramatic foreshortening." },
  { id: "cyberpunk", label: "Cyberpunk", promptSuffix: "Rendered in a cyberpunk aesthetic: neon-accented lighting treatment in magenta and cyan, high-contrast reflective surfaces, and a gritty high-tech finish.", promptSuffixReference: "Reimagine this scene in a cyberpunk aesthetic: neon-accented lighting treatment in magenta and cyan, high-contrast reflective surfaces, and a gritty high-tech finish." },
  { id: "pixel-art", label: "Pixel Art", promptSuffix: "Created as detailed 32-bit pixel art: clean sprite work, a limited color palette, visible pixel grid, and a retro video game look.", promptSuffixReference: "Reimagine this as detailed 32-bit pixel art: clean sprite work, a limited color palette, visible pixel grid, and a retro video game look." },
  { id: "oil-painting", label: "Oil Painting", promptSuffix: "Rendered as a classical oil painting: visible brushstrokes, rich impasto texture, and Rembrandt-style chiaroscuro.", promptSuffixReference: "Transform this into a classical oil painting: visible brushstrokes, rich impasto texture, and Rembrandt-style chiaroscuro." },
  { id: "propaganda", label: "Propaganda Poster", promptSuffix: "Designed as a bold Soviet-era propaganda poster: flat limited palette of red, black, cream, and gold, strong geometric composition, and blocky stylized figures.", promptSuffixReference: "Reimagine this as a bold Soviet-era propaganda poster: flat limited palette of red, black, cream, and gold, strong geometric composition, and blocky stylized figures." },
  { id: "pop-art", label: "Pop Art", promptSuffix: "Illustrated in Warhol-inspired pop art style: bold primary colors, Ben-Day dots, thick black outlines, and flat graphic shapes.", promptSuffixReference: "Transform this into Warhol-inspired pop art style: bold primary colors, Ben-Day dots, thick black outlines, and flat graphic shapes." },
  { id: "watercolor", label: "Watercolor", promptSuffix: "Painted in loose expressive watercolor: soft wet-on-wet color bleeds, visible paper texture, delicate washes, and intentional white space.", promptSuffixReference: "Reimagine this in loose expressive watercolor: soft wet-on-wet color bleeds, visible paper texture, delicate washes, and intentional white space." },
  { id: "photorealistic", label: "Photorealistic", promptSuffix: "Rendered as a hyper-photorealistic photograph: true-to-life materials and textures, realistic optical detail, and high-end camera clarity.", promptSuffixReference: "Reimagine this as a hyper-photorealistic photograph: true-to-life materials and textures, realistic optical detail, and high-end camera clarity." },
  { id: "graffiti", label: "Graffiti / Street Art", promptSuffix: "Created as vibrant street art: spray-paint textures with drips, stencil layers, and bold graphic energy on a weathered concrete-wall surface.", promptSuffixReference: "Transform this into vibrant street art: spray-paint textures with drips, stencil layers, and bold graphic energy on a weathered concrete-wall surface." },
  { id: "sketch", label: "Sketch / Blueprint", promptSuffix: "Drawn as a detailed technical pencil sketch on aged parchment: cross-hatching, visible construction lines, and inventor's-notebook draftsmanship.", promptSuffixReference: "Reimagine this as a detailed technical pencil sketch on aged parchment: cross-hatching, visible construction lines, and inventor's-notebook draftsmanship." },
  { id: "pulp-fiction", label: "Retro Pulp Fiction", promptSuffix: "Illustrated in 1950s pulp magazine cover style: painted texture, saturated lurid color treatment, and melodramatic vintage illustration flair.", promptSuffixReference: "Transform this into 1950s pulp magazine cover style: painted texture, saturated lurid color treatment, and melodramatic vintage illustration flair." },
  { id: "stained-glass", label: "Stained Glass", promptSuffix: "Depicted as an ornate stained glass window: bold black leading lines, jewel-tone translucent glass segments, and radiant backlighting.", promptSuffixReference: "Reimagine this as an ornate stained glass window: bold black leading lines, jewel-tone translucent glass segments, and radiant backlighting." },
  { id: "claymation", label: "Claymation", promptSuffix: "Rendered as stop-motion claymation: visible fingerprint textures in clay, slightly imperfect sculpted forms, and a miniature practical-set look.", promptSuffixReference: "Reimagine this as stop-motion claymation: visible fingerprint textures in clay, slightly imperfect sculpted forms, and a miniature practical-set look." },
  { id: "ukiyo-e", label: "Ukiyo-e (Japanese Woodblock)", promptSuffix: "Illustrated in traditional Japanese ukiyo-e woodblock style: flat color areas, bold flowing outlines, woodblock print texture, and a muted natural pigment palette.", promptSuffixReference: "Reimagine this in traditional Japanese ukiyo-e woodblock style: flat color areas, bold flowing outlines, woodblock print texture, and a muted natural pigment palette." },
  { id: "neon-noir", label: "Neon Noir", promptSuffix: "Rendered in neon noir style: deep black shadows cut by neon glow accents, film grain, and a moody high-contrast noir treatment.", promptSuffixReference: "Reimagine this scene in neon noir style: deep black shadows cut by neon glow accents, film grain, and a moody high-contrast noir treatment." },
];

export const IMAGE_STYLE_MAP = new Map(IMAGE_STYLES.map(s => [s.id, s]));
