/**
 * Phase 2 — structured moderator visual-strategy override.
 *
 * A per-fact, style-agnostic, token-aware object a human moderator edits to
 * correct/sharpen the AI's first-pass visual strategy WITHOUT editing the brittle
 * final Nano Banana prompt. Stored nested in the `FactEnrichment` blob
 * (`enrichment.visualPromptStrategyOverride`) and merged into the deterministic
 * compiler's labeled sections at render time, so the final prompt still adapts to
 * subject/pronouns, reference image, style, render mode, aspect ratio, and the
 * Phase 1 render policy.
 *
 * Token model: moderator text fields may carry the same personalization tokens as
 * fact templates ({NAME}, {NAME_POSSESSIVE}, {SUBJ}, …). On save we canonicalize
 * the name-token case/possessive variants ({name}/{Name} → {NAME},
 * {name_possessive} → {NAME_POSSESSIVE}) and reject any UNKNOWN token with a clear
 * message; the compiler renders the rest per render via `renderPersonalized`.
 *
 * This module is dependency-light on purpose (only the leaf render-policy enums +
 * the template grammar) so `taxonomy.ts` can embed it without an import cycle.
 */

import { z } from "zod";
import {
  SUPPORTING_TEXT_MODE_VALUES,
  VIOLENCE_MODE_VALUES,
  VIOLENCE_INTENSITY_VALUES,
} from "./renderPolicyEnums";
import { validateTemplate } from "./templateGrammar";

// ─── Subject realization modes ──────────────────────────────────────────────

export const SUBJECT_REALIZATION_MODE_VALUES = [
  "use_ai_plan", // default — keep the AI's subject realization; the rest of the override still applies
  "normal_human",
  "age_transformed_human",
  "adult_head_on_transformed_body",
  "subject_as_object",
  "nonhuman_transformation",
  "symbolic_or_implied",
  "custom",
] as const;
export type SubjectRealizationMode = (typeof SUBJECT_REALIZATION_MODE_VALUES)[number];

export const VISUAL_STRATEGY_OVERRIDE_VERSION = 1 as const;

// ─── Schema ─────────────────────────────────────────────────────────────────

const roleBindingSchema = z.object({
  entity: z.string(), // "subject" or a relationship/name/type label ("mother", "crowd/victims")
  visualRole: z.string(),
});

const subjectRealizationOverrideSchema = z.object({
  mode: z.enum(SUBJECT_REALIZATION_MODE_VALUES),
  description: z.string(),
});

const supportingTextPolicyOverrideSchema = z.object({
  mode: z.enum(SUPPORTING_TEXT_MODE_VALUES),
  guidance: z.string().optional(),
});

const violencePolicyOverrideSchema = z.object({
  mode: z.enum(VIOLENCE_MODE_VALUES),
  intensity: z.enum(VIOLENCE_INTENSITY_VALUES),
  guidance: z.string().optional(),
});

// Shape only (no transform/refine) so the object can be reasoned about + the
// token transform/refine layered on top in `visualPromptStrategyOverrideSchema`.
const visualPromptStrategyOverrideBase = z.object({
  version: z.literal(VISUAL_STRATEGY_OVERRIDE_VERSION),
  enabled: z.boolean(),
  moderatorIntent: z.string().optional(),
  /**
   * Moderator-authored CORE SCENE ("describe the picture"). When non-empty it
   * is the AUTHORITATIVE scene: the planner LLM is directed to realize it and
   * the compiler emits it as the required, non-compressible CORE SCENE section
   * (winning over the AI plan's coreScene). Carries {NAME}/pronoun tokens.
   * Capped: the engine prompt budget is 4000 chars and this section is never
   * compressed — it is a scene brief, not a full prompt.
   */
  coreSceneOverride: z.string().max(1500).optional(),
  subjectRealizationOverride: subjectRealizationOverrideSchema.optional(),
  requiredVisualDetails: z.array(z.string()).max(40).default([]),
  forbiddenVisualDetails: z.array(z.string()).max(40).default([]),
  roleBindings: z.array(roleBindingSchema).max(20).default([]),
  compositionGuidance: z.array(z.string()).max(20).default([]),
  styleAgnosticPromptAdditions: z.array(z.string()).max(20).default([]),
  negativePromptAdditions: z.array(z.string()).max(20).default([]),
  supportingTextPolicyOverride: supportingTextPolicyOverrideSchema.optional(),
  violencePolicyOverride: violencePolicyOverrideSchema.optional(),
  notesForModerator: z.string().optional(),
  // Server-owned provenance — stamped by the admin save path, preserved verbatim
  // across re-classification, never generated by the AI.
  updatedBy: z.string().optional(),
  updatedAt: z.string().optional(),
});

export type VisualPromptStrategyOverride = z.infer<typeof visualPromptStrategyOverrideBase>;
export type VisualStrategyRoleBinding = z.infer<typeof roleBindingSchema>;

// ─── Token handling ─────────────────────────────────────────────────────────

/** Fields whose text is RENDERED into the engine prompt (so tokens matter).
 *  `moderatorIntent` / `notesForModerator` are admin-only and never emitted. */
function collectRenderedTexts(ov: VisualPromptStrategyOverride): string[] {
  const out: string[] = [];
  if (ov.coreSceneOverride) out.push(ov.coreSceneOverride);
  if (ov.subjectRealizationOverride?.description) out.push(ov.subjectRealizationOverride.description);
  out.push(...ov.requiredVisualDetails, ...ov.forbiddenVisualDetails, ...ov.compositionGuidance);
  out.push(...ov.styleAgnosticPromptAdditions, ...ov.negativePromptAdditions);
  for (const rb of ov.roleBindings) out.push(rb.entity, rb.visualRole);
  if (ov.supportingTextPolicyOverride?.guidance) out.push(ov.supportingTextPolicyOverride.guidance);
  if (ov.violencePolicyOverride?.guidance) out.push(ov.violencePolicyOverride.guidance);
  return out;
}

/** Canonicalize the name-token case variants {name}/{Name} → {NAME} and the
 *  possessive variants {name_possessive}/{Name_Possessive}/… → {NAME_POSSESSIVE}.
 *  The other personalization (pronoun) tokens have meaningful case variants and
 *  are left alone. Possessive is canonicalized first so the bare-{NAME} pass
 *  can't partially touch it. */
export function canonicalizeNameToken(text: string): string {
  return text
    .replace(/\{(?:name|Name|NAME)_(?:possessive|Possessive|POSSESSIVE)\}/g, "{NAME_POSSESSIVE}")
    .replace(/\{(?:name|Name)\}/g, "{NAME}");
}

function mapText(text: string): string {
  return canonicalizeNameToken(text);
}

/** Return the canonicalized override (name-token variants normalized in every
 *  rendered field). Pure; used by the schema transform on save. */
export function canonicalizeOverrideTokens(
  ov: VisualPromptStrategyOverride,
): VisualPromptStrategyOverride {
  return {
    ...ov,
    coreSceneOverride: ov.coreSceneOverride != null ? mapText(ov.coreSceneOverride) : ov.coreSceneOverride,
    subjectRealizationOverride: ov.subjectRealizationOverride
      ? { ...ov.subjectRealizationOverride, description: mapText(ov.subjectRealizationOverride.description) }
      : ov.subjectRealizationOverride,
    requiredVisualDetails: ov.requiredVisualDetails.map(mapText),
    forbiddenVisualDetails: ov.forbiddenVisualDetails.map(mapText),
    compositionGuidance: ov.compositionGuidance.map(mapText),
    styleAgnosticPromptAdditions: ov.styleAgnosticPromptAdditions.map(mapText),
    negativePromptAdditions: ov.negativePromptAdditions.map(mapText),
    roleBindings: ov.roleBindings.map((rb) => ({ entity: mapText(rb.entity), visualRole: mapText(rb.visualRole) })),
    supportingTextPolicyOverride: ov.supportingTextPolicyOverride?.guidance
      ? { ...ov.supportingTextPolicyOverride, guidance: mapText(ov.supportingTextPolicyOverride.guidance) }
      : ov.supportingTextPolicyOverride,
    violencePolicyOverride: ov.violencePolicyOverride?.guidance
      ? { ...ov.violencePolicyOverride, guidance: mapText(ov.violencePolicyOverride.guidance) }
      : ov.violencePolicyOverride,
  };
}

/** First unknown-token error across the override's rendered text fields, or null.
 *  Empty/whitespace strings are skipped (mid-edit rows). Assumes name-case
 *  variants were already canonicalized. */
export function firstOverrideTokenError(ov: VisualPromptStrategyOverride): string | null {
  for (const text of collectRenderedTexts(ov)) {
    const t = text.trim();
    if (!t || !t.includes("{")) continue;
    const res = validateTemplate(t);
    if (!res.valid) return res.error ?? "invalid token";
  }
  return null;
}

export const visualPromptStrategyOverrideSchema = visualPromptStrategyOverrideBase
  .transform(canonicalizeOverrideTokens)
  .superRefine((ov, ctx) => {
    const err = firstOverrideTokenError(ov);
    if (err) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: `visual strategy override has an invalid personalization token: ${err}. Use {NAME}, {NAME_POSSESSIVE}, and pronoun tokens only.`,
      });
    }
  });

/**
 * True when the override carries any content that is RENDERED into the engine
 * prompt. The single source of truth for "enabled but empty" style checks so
 * UI surfaces can't drift on what counts as content. Admin-only fields
 * (moderatorIntent, notesForModerator) deliberately do NOT count.
 */
export function hasRenderableVisualStrategyOverrideContent(
  ov: VisualPromptStrategyOverride,
): boolean {
  if (ov.supportingTextPolicyOverride || ov.violencePolicyOverride) return true;
  if (ov.subjectRealizationOverride && ov.subjectRealizationOverride.mode !== "use_ai_plan") return true;
  return collectRenderedTexts(ov).some((t) => t.trim().length > 0);
}

/** A disabled-but-present override scaffold (all lists empty). */
export const EMPTY_VISUAL_STRATEGY_OVERRIDE: VisualPromptStrategyOverride = {
  version: VISUAL_STRATEGY_OVERRIDE_VERSION,
  enabled: false,
  requiredVisualDetails: [],
  forbiddenVisualDetails: [],
  roleBindings: [],
  compositionGuidance: [],
  styleAgnosticPromptAdditions: [],
  negativePromptAdditions: [],
};
