/**
 * check-migration-snapshots.ts
 *
 * Verifies that every entry in _journal.json has a corresponding
 * `{prefix}_snapshot.json` file in the same meta/ directory.
 *
 * Drizzle-kit generates a snapshot alongside each DDL migration it creates.
 * Manually crafted or DML-only migrations that pre-date this check do not
 * have snapshots; they are listed in SNAPSHOT_EXEMPT_TAGS below.
 *
 * Any journal entry NOT in the exempt list and WITHOUT a snapshot file causes
 * this script to exit 1 with a clear message naming each missing snapshot.
 *
 * Usage:
 *   pnpm --filter @workspace/db check-snapshots
 *   node --import tsx/esm lib/db/scripts/check-migration-snapshots.ts
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const META_DIR = path.resolve(__dirname, "../migrations/meta");
const JOURNAL_PATH = path.join(META_DIR, "_journal.json");

/**
 * Full tags of journal entries that are known to be snapshot-less.
 *
 * These are DML-only migrations, manually authored migrations written before
 * drizzle-kit snapshot tracking was in place, or migrations where the snapshot
 * was intentionally omitted. Adding a tag here is an explicit acknowledgement
 * that the missing snapshot is expected.
 *
 * DO NOT add new tags here without a clear reason — the whole point of this
 * check is to catch accidental omissions before they reach production.
 */
const SNAPSHOT_EXEMPT_TAGS = new Set<string>([
  "0001_soft_delete_facts_users",
  "0001b_add_canonical_text_to_facts",
  "0002_add_comment_activity_types",
  "0003_memes_image_source",
  "0004_remove_cafepress_destination",
  "0004b_pexels_images",
  "0005_memes_is_public",
  "0006_memes_image_metadata",
  "0007_upload_image_user_id",
  "0008_user_ai_images",
  "0009_admin_config",
  "0010_video_jobs",
  "0011_video_jobs_style_id",
  "0012_admin_config_labels",
  "0013_feature_flags",
  "0014_legendary_generation_limit",
  "0017_route_stats",
  "0022_email_outbox",
  "0024_review_reason_enum",
  "0025_review_reason_spam_offensive",
  "0027_review_reason_lame",
  "0028_upload_photo_registered",
  "0029_permissions_cleanup",
  "0030_stripe_webhook_audit",
  "0030_rate_limit_counters",
  "0032_checkout_request_ledger",
  "0033_user_fact_pref_seen_as_hero",
  "0034_affiliate_clicks_source",
  "0035_reactions_polymorphic",
  "0036_oauth_pending_states",
  "0037_email_outbox_status_created_idx",
  "0039_oauth_pending_states_link_user_id",
  "0040_oauth_multi_provider",
]);

interface JournalEntry {
  idx: number;
  version: string;
  when: number;
  tag: string;
  breakpoints: boolean;
}

interface Journal {
  version: string;
  dialect: string;
  entries: JournalEntry[];
}

function snapshotFilename(tag: string): string {
  const prefix = tag.split("_")[0];
  return `${prefix}_snapshot.json`;
}

function run(): void {
  if (!fs.existsSync(JOURNAL_PATH)) {
    console.error(`ERROR: Journal not found at ${JOURNAL_PATH}`);
    process.exit(1);
  }

  const journal: Journal = JSON.parse(fs.readFileSync(JOURNAL_PATH, "utf-8"));
  const missing: string[] = [];

  for (const entry of journal.entries) {
    if (SNAPSHOT_EXEMPT_TAGS.has(entry.tag)) {
      continue;
    }

    const snapshotFile = path.join(META_DIR, snapshotFilename(entry.tag));
    if (!fs.existsSync(snapshotFile)) {
      missing.push(
        `  idx=${entry.idx}  tag=${entry.tag}  expected=${snapshotFilename(entry.tag)}`,
      );
    }
  }

  if (missing.length === 0) {
    console.log(
      `✓ All ${journal.entries.length} journal entries have snapshot files (or are explicitly exempt).`,
    );
    process.exit(0);
  }

  console.error(
    `\nMigration snapshot check FAILED — ${missing.length} non-exempt journal ${
      missing.length === 1 ? "entry is" : "entries are"
    } missing a snapshot file.\n`,
  );
  console.error(
    "Each DDL migration generated by drizzle-kit should produce a",
    "corresponding meta/{prefix}_snapshot.json file.\n",
  );
  console.error("Missing:");
  for (const line of missing) {
    console.error(line);
  }
  console.error(
    "\nFix: run `pnpm --filter @workspace/db generate` to regenerate snapshots,",
    "or add the tag to SNAPSHOT_EXEMPT_TAGS in",
    "lib/db/scripts/check-migration-snapshots.ts if the omission is intentional.",
  );
  process.exit(1);
}

run();
