/**
 * check-migration-snapshots.ts
 *
 * Verifies that every entry in _journal.json has a corresponding
 * `{prefix}_snapshot.json` file in the same meta/ directory.
 *
 * Drizzle-kit generates a snapshot alongside each DDL migration it creates.
 * Manually crafted or DML-only migrations that pre-date this check do not
 * have snapshots; they are listed in SNAPSHOT_EXEMPT_TAGS below.
 *
 * Any journal entry NOT in the exempt list and WITHOUT a snapshot file causes
 * this script to exit 1 with a clear message naming each missing snapshot.
 *
 * Usage:
 *   pnpm --filter @workspace/db check-snapshots
 *   node --import tsx/esm lib/db/scripts/check-migration-snapshots.ts
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const META_DIR = path.resolve(__dirname, "../migrations/meta");
const JOURNAL_PATH = path.join(META_DIR, "_journal.json");

/**
 * Full tags of journal entries that are known to be snapshot-less.
 *
 * These are DML-only migrations, manually authored migrations written before
 * drizzle-kit snapshot tracking was in place, or migrations where the snapshot
 * was intentionally omitted. Adding a tag here is an explicit acknowledgement
 * that the missing snapshot is expected.
 *
 * DO NOT add new tags here without a clear reason — the whole point of this
 * check is to catch accidental omissions before they reach production.
 */
const SNAPSHOT_EXEMPT_TAGS = new Set<string>([
  // All previously-exempt tags (0001–0037) have been backfilled with approximate
  // snapshots derived from the next available snapshot in the chain. The exempt
  // list is now empty; keep this set in place so new intentional omissions can
  // be added with an explicit comment explaining why.
]);

interface JournalEntry {
  idx: number;
  version: string;
  when: number;
  tag: string;
  breakpoints: boolean;
}

interface Journal {
  version: string;
  dialect: string;
  entries: JournalEntry[];
}

function snapshotFilename(tag: string): string {
  const prefix = tag.split("_")[0];
  return `${prefix}_snapshot.json`;
}

function run(): void {
  if (!fs.existsSync(JOURNAL_PATH)) {
    console.error(`ERROR: Journal not found at ${JOURNAL_PATH}`);
    process.exit(1);
  }

  const journal: Journal = JSON.parse(fs.readFileSync(JOURNAL_PATH, "utf-8"));
  const missing: string[] = [];

  for (const entry of journal.entries) {
    if (SNAPSHOT_EXEMPT_TAGS.has(entry.tag)) {
      continue;
    }

    const snapshotFile = path.join(META_DIR, snapshotFilename(entry.tag));
    if (!fs.existsSync(snapshotFile)) {
      missing.push(
        `  idx=${entry.idx}  tag=${entry.tag}  expected=${snapshotFilename(entry.tag)}`,
      );
    }
  }

  if (missing.length === 0) {
    console.log(
      `✓ All ${journal.entries.length} journal entries have snapshot files (or are explicitly exempt).`,
    );
    process.exit(0);
  }

  console.error(
    `\nMigration snapshot check FAILED — ${missing.length} non-exempt journal ${
      missing.length === 1 ? "entry is" : "entries are"
    } missing a snapshot file.\n`,
  );
  console.error(
    "Each DDL migration generated by drizzle-kit should produce a",
    "corresponding meta/{prefix}_snapshot.json file.\n",
  );
  console.error("Missing:");
  for (const line of missing) {
    console.error(line);
  }
  console.error(
    "\nFix: run `pnpm --filter @workspace/db generate` to regenerate snapshots,",
    "or add the tag to SNAPSHOT_EXEMPT_TAGS in",
    "lib/db/scripts/check-migration-snapshots.ts if the omission is intentional.",
  );
  process.exit(1);
}

run();
